replicaCount: 1

environment:
  baseUrl: https://api-dev.satoshipay.io/staging/signature-coordinator
  mainnetHorizonUrl: https://stellar-horizon.satoshipay.io
  testnetHorizonUrl: https://stellar-horizon-testnet.satoshipay.io
  # databaseUrl

postgresql:
  postgresqlUsername: postgres
  # postgresqlPassword
  postgresqlDatabase: coordinator
  persistence:
    storageClass: standard

image:
  repository: satoshipay/multisig-coordinator
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  # e.g. backend annotations from https://docs.traefik.io/configuration/backends/kubernetes/#general-annotations
  annotations: {}

ingress:
  enabled: true
  # e.g. frontend annotations from https://docs.traefik.io/configuration/backends/kubernetes/#general-annotations
  annotations:
    kubernetes.io/ingress.class: traefik
  # host
  path: /signature-coordinator

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
