{{- if .Values.application.migrate.run -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "trackableappname" . }}-db-migrate
  labels:
    app: {{ template "appname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      initContainers:
        - name: init-postgres
          image: governmentpaas/psql
          command: ['sh', '-c', 'until psql "postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.postgresqlDatabase }}" -c "SELECT 1"; do echo "waiting for postgres"; sleep 2; done;']
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.application.migrate.image }}
        command: ["/bin/sh"]
        args: ["-c", {{ .Values.application.migrate.command | quote }}]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: migrations
            mountPath: /migrations
        {{- if .Values.application.secretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        env:
        - name: DATABASE_USER
          value: {{ .Values.postgresql.postgresqlUsername | quote }}
        - name: DATABASE_NAME
          value: {{ .Values.postgresql.postgresqlDatabase | quote }}
        - name: DATABASE_PASSWORD
          value: {{ .Values.postgresql.postgresqlPassword | quote }}
        - name: DATABASE_SERVER
          value: {{ .Release.Name }}-postgresql
      volumes:
      - name: migrations
        configMap:
          name: {{ template "name" . }}-migrations
{{- end -}}
