apiVersion: v1
kind: Service
metadata:
  name: {{ template "signature-coordinator.fullname" . }}
  labels:
    app: {{ template "signature-coordinator.name" . }}
    chart: {{ template "signature-coordinator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-api
      protocol: TCP
      name: http
  selector:
    app: {{ template "signature-coordinator.name" . }}
    release: {{ .Release.Name }}
